### PR TITLE
feat: Session notes Static Functionalities

### PR DESCRIPTION
**Pull request by yogesh7401**
Added Static functionalities in session page

Yet to done
- [ ] Make it dynamic
- [ ] Dragable Sessions and Topic

### CODE REVIEW

**Comment by anburocky3** [comment]
Cool work. Loved it. But i like the dialog to be wide enough. Currently the width of the modal is small. But it can be little wider.

Also, regarding XP, viewing the notes can be improved.

**Comment by yogesh7401** [comment]
Okay @anburocky3 👍

**Comment by yogesh7401** [comment]
Is it good if we make taking notes in markdown format ?

**Comment by anburocky3** [comment]
> Is it good if we make taking notes in markdown format ?

Good but, we need some formatters available. So when i click or press CTRL + S, it should automatically format.

**Comment by yogesh7401** [comment]
Added drag and drop in #3

**Pull request closed without merging**
